builds:
  - binary: j8a
    main: cmd/j8a/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm64/v8
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: j8a
    homepage: "https://github.com/simonmittag/j8a"
    tap:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com

dockers:
  - goarch: amd64
    goos: linux
    image_templates:
      - 'docker.io/simonmittag/j8a:{{.Tag}}-amd64'
  - goarch: arm64
    goos: linux
    image_templates:
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64'
  - goarch: arm64/v8
    goos: linux
    image_templates:
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64-v8'

docker_manifests:
  - name_template: 'docker.io/simonmittag/j8a:{{.Tag}}'
    image_templates:
      - 'docker.io/simonmittag/j8a:{{.Tag}}-amd64'
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64'
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64-v8'
  - name_template: 'docker.io/simonmittag/j8a:latest'
    image_templates:
      - 'docker.io/simonmittag/j8a:{{.Tag}}-amd64'
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64'
      - 'docker.io/simonmittag/j8a:{{.Tag}}-arm64-v8'

checksum:
  name_template: 'checksums.txt'