builds:
  - binary: j8a
    main: cmd/j8a/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: j8a
    homepage: "https://github.com/simonmittag/j8a"
    tap:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com

dockers:
  - image_templates:
      - "docker.io/simonmittag/j8a:{{.Tag}}"

checksum:
  name_template: 'checksums.txt'