version: 2

builds:
  - binary: j8a
    main: cmd/j8a/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  draft: false
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: j8a
    homepage: "https://github.com/simonmittag/j8a"
    repository:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com

docker_build:
  - dockerfile: Dockerfile
    context: .
    use: buildx
    image_templates:
      - docker.io/simonmittag/j8a:{{ .Tag }}-{{ .Arch }}
    platforms:
      - linux/amd64
      - linux/arm64
    build_flag_templates:
      - "--pull"

docker_manifests:
  - name_template: docker.io/simonmittag/j8a:{{.Tag}}
    image_templates:
      - docker.io/simonmittag/j8a:{{.Tag}}-amd64
      - docker.io/simonmittag/j8a:{{.Tag}}-arm64

  - name_template: docker.io/simonmittag/j8a:latest
    image_templates:
      - docker.io/simonmittag/j8a:{{.Tag}}-amd64
      - docker.io/simonmittag/j8a:{{.Tag}}-arm64

checksum:
  name_template: 'checksums.txt'
